### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by Kadantte** [trekhleb/covid-19#18]
Make an option to get chart to show from the start showing a country ex: "USA"

**Comment by trekhleb** [comment]
It is possible now. Whenever you select a filter (i.e. by country) the URL is being changes so that you may copy it and send it to anyone and the filters (i.e. country) will be pre-selected. Here is an example with selected US by default: https://trekhleb.github.io/covid-19/?selectedRegions=%5B%22US%22%5D

**Comment by Kadantte** [comment]
Thank's for the Update.
