### ISSUE TITLE
Display the confirmed/recovered/deaths cases per capita

### ISSUE THREAD

**Issue by trekhleb** [trekhleb/covid-19#19]
According to the comment from Thomas Soos here: https://dev.to/thomassalty/comment/n59a

> There's one thing I always think about seeing these numbers which is the percentage of cases according to the population of the countries. Because let's say 80.000 cases in China is very different from 80.000 cases in Italy, whose population is much, much less. So in my opinion, it would be a nice addition to see the percentages in the Bootstrap Table in a new column.

**Comment by melvinsalas** [comment]
I will try to make a fork using the population data of https://github.com/datasets/population

**Comment by trekhleb** [comment]
Closing this issue in favour of https://github.com/trekhleb/covid-19/issues/23

**Comment by trekhleb** [comment]
The following data-set might also be considered: https://www.kaggle.com/sudalairajkumar/undata-country-profiles

**Comment by ThomasSalty** [comment]
Hi @trekhleb and @melvinsalas!

Wow, this was really quick you guys. However I didn't mean the mortality rate in my comment, I meant the infected rate or confirmed cases per capita.

For example if Italy has a population of 60 million and 100k is infected, then the percentage is (100k / 60m) * 100 = 0.16%.
If the US has a population of 330 million and 160k is infected that means ~ 0.05% of the total population is infected. The bigger the population, the smaller the infected rate for the same number of infected people. Of course these numbers for the population and the total confirmed cases/country change over time, so this has to be dynamic in order to be accurate as time goes by.
I'm sorry, I know my comment wasn't very precise on that...
